import React from 'react';
import { Post } from '../types';

interface PostListProps {
  posts: Post[];
}

const PostList: React.FC<PostListProps> = ({ posts }) => {

  const sortedPosts = [...posts].sort((a, b) => new Date(b.scheduleDate).getTime() - new Date(a.scheduleDate).getTime());

  const PostCard = ({ post }: { post: Post }) => (
    <div className="bg-slate-900/70 rounded-lg p-4 border border-slate-700 flex flex-col md:flex-row gap-4 items-start">
      <div className="flex-shrink-0 w-full md:w-32 h-32">
        {post.mediaType.startsWith('video') ? (
          <video src={post.mediaUrl} className="w-full h-full object-cover rounded-md bg-black" />
        ) : (
          <img src={post.mediaUrl} alt="Post preview" className="w-full h-full object-cover rounded-md bg-black" />
        )}
      </div>
      <div className="flex-grow">
        <div className="flex items-center justify-between mb-2">
           <span className={`px-2 py-1 text-xs font-semibold rounded-full ${
              post.status === 'Posted' ? 'bg-green-500/20 text-green-300' : 'bg-cyan-500/20 text-cyan-300'
           }`}>
            {post.status}
          </span>
          <span className="text-sm text-slate-400">
            {new Date(post.scheduleDate).toLocaleString()}
          </span>
        </div>
        {post.caption ? (
          <p className="text-sm text-slate-300 bg-slate-800/50 p-3 rounded-md whitespace-pre-wrap">{post.caption}</p>
        ) : (
          <p className="text-sm text-slate-500 italic">Caption will be generated by AI upon posting.</p>
        )}
      </div>
    </div>
  );

  return (
    <div className="bg-slate-800/50 rounded-xl p-6 shadow-lg border border-slate-700">
      <h2 className="text-xl font-bold text-slate-200 mb-4">Your Posts</h2>
      {posts.length === 0 ? (
        <div className="text-center text-slate-500 py-10">
          <svg xmlns="http://www.w3.org/2000/svg" className="mx-auto h-12 w-12" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1">
            <path strokeLinecap="round" strokeLinejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
          </svg>
          <p className="mt-2">You have no scheduled posts.</p>
          <p className="text-sm">Use the form above to schedule your first one!</p>
        </div>
      ) : (
        <div className="space-y-4 max-h-[500px] overflow-y-auto pr-2">
            {sortedPosts.map(post => <PostCard key={post.id} post={post} />)}
        </div>
      )}
    </div>
  );
};

export default PostList;